version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: main
    schedule:
      interval: daily
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /
    target-branch: main
    schedule:
      interval: daily
    groups:
      actions:
        patterns:
          - "*"
