name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  UV_FROZEN: 1

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4.2.2

      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files

      - uses: astral-sh/setup-uv@v5.3.0
        with:
          enable-cache: true
          python-version: "3.13"
          version: latest

      - name: pytest
        run: uv run pytest

      - name: basedpyright
        run: uv run basedpyright --threads 2

      - name: unstub numpy
        run: uv run tool/unstub.py

      - name: mypy
        run: >
          uv run --no-editable
          mypy --explicit-package-bases .

      - name: stubtest
        run: >
          uv run --no-editable
          stubtest
          --mypy-config-file=pyproject.toml
          --allowlist=.mypyignore
          --allowlist=.mypyignore-todo
          numpy
