name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  UV_FROZEN: 1

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - uses: actions/checkout@v4

      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: 3.13t

      - name: pytest
        run: uv run --no-group=orjson pytest

  basedpyright:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: 3.13t

      - name: basedpyright
        run: >
          uv run --no-group=orjson
          basedpyright --threads=3

  mypy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: 3.13

      - name: mypy
        run: >
          uv run --no-group=numpy
          mypy --no-incremental test

  stubtest:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: 3.13

      - name: unstub numpy
        run: >
          uv run --no-editable
          tool/unstub.py

      - name: stubtest
        run: >
          uv run --no-editable
          stubtest
          --mypy-config-file=pyproject.toml
          --allowlist=.mypyignore
          --allowlist=.mypyignore-todo
          --concise
          numpy
