name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  UV_FROZEN: 1

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - name: typos
        uses: crate-ci/typos@master

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: "3.13"
          version: latest

      - name: ruff
        run: |
          uv run ruff check --output-format=github
          uv run ruff format --check

      - name: test static (sanity)
        run: uv run --directory test static all static/sanity

      - name: test static (reject)
        run: uv run --directory test static all static/reject

      - name: test static (accept)
        run: uv run --directory test static all static/accept
        continue-on-error: true  # TODO
