name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  UV_FROZEN: 1

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - uses: actions/checkout@v4

      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: 3.13t

      - name: pytest
        run: uv run --no-group=orjson pytest

  basedpyright:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        py: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: ${{ matrix.py }}

      - name: basedpyright (python ${{ matrix.py }})
        run: >
          uv run --no-group=orjson
          basedpyright --threads=3

  mypy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        py: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: ${{ matrix.py }}

      - name: mypy (python ${{ matrix.py }})
        run: >
          uv run --no-group=numpy
          mypy test

  stubtest:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        py: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: ${{ matrix.py }}

      - name: stubtest (python ${{ matrix.py }})
        run: >
          uv run --active -p ${{ matrix.py }}
          tool/stubtest.py
