name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  UV_FROZEN: 1

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: typos
        uses: crate-ci/typos@master

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: "3.13"
          version: latest

      - name: ruff check
        run: uv run ruff check --output-format=github

      - name: ruff format --check
        run: uv run ruff format --check

      - name: pytest
        run: uv run pytest

      - name: basedpyright
        run: uv run basedpyright

      - name: mypy (src)
        run: uv run test/mypy.py src

      - name: mypy (test)
        run: uv run test/mypy.py

      - name: stubtest
        run: uv run tool/stubtest.py
